export const ADD_CARDS_STARTED = 'ADD_CARDS_STARTED';
export const ADD_CARDS_SUCCESS = 'ADD_CARDS_SUCCESS';
export const ADD_CARDS_FAILURE = 'ADD_CARDS_FAILURE';

export const SET_CARDS_FILTER = 'SET_CARDS_FILTER';
